# Generated by Django 4.1.5 on 2023-01-11 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_telegramuser_light_registeredusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='luxLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='light',
            name='motionDetected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='light',
            name='overrideMotionSensor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='notificationEndTime',
            field=models.TimeField(default=datetime.time(11, 59, 59)),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='notificationStartTime',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='light',
            name='isOn',
            field=models.BooleanField(default=False),
        ),
    ]
