# Generated by Django 4.1.5 on 2023-01-15 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_light_luxlevel_light_motiondetected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='notificationEndTime',
            field=models.TimeField(default=datetime.time(23, 59, 59)),
        ),
    ]
