# Generated by Django 4.1.5 on 2023-01-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_alter_telegramuser_notificationendtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='numberOfOkays',
            field=models.IntegerField(default=0),
        ),
    ]
